### PR TITLE
Adding stopforumspam and MISP IP check to feeds

### PR DESCRIPTION
**Pull request by nicolasvillatte**
I have cleaned up the conflicts, should be good to go now.

Kind regards,
Nicolas.

### CODE REVIEW

**Comment by ChrisTruncer** [comment]
Wow, I've completely missed this pull request, I apologize for that.  I'd love to get this added in, but it looks like there are some conflicts.  Would you mind fixing them?

Once you do, I can get this merged in.

Sorry for taking so long on this, I just saw you had opened this request.

**Comment by nicolasvillatte** [comment]
Will do when I have some time to rewrite

**Comment by ChrisTruncer** [comment]
Thank you,

I apologize again for not seeing this earlier, but I should now be alerted the second an update it pushed to it. Once that happens, I should be able to add this in pretty quickly.

Thanks

**Comment by ChrisTruncer** [comment]
Also, this looks to be fairly quick, I can help with this also if you need it.  Worst case, I can submit a patch to you, and then you can push that into this PR (to make sure that you get credit for sending it this way).

Thanks again

**Comment by nicolasvillatte** [comment]
As you wish. I will be fairly busy in the coming weeks.

**Comment by ChrisTruncer** [comment]
OK, so I made a new branch (located at: https://github.com/ChrisTruncer/Just-Metadata/tree/pull_14).  This should include the MIPS check that you added in.  If you want, just copy the files from there and add it into your pull request, and I can get it merged in (I want to make sure you get the credit for being the original author).

Also, just a note, this is gathering the information, but at the moment it isn't doing anything with it.  The analysis module is what would parse this information and print something out to the user, but that hasn't been modified (since it wasn't in your original pull request).  So I'm not sure if that's something you wanted to do in a different pull request, or if you'd like me to, but I just wanted to make you aware of it.

Once you get these changes added into your pull request, then I should be able to get this merged.  Thanks again for your help

**Comment by nicolasvillatte** [comment]
modified the files on this pull request with the ones from pull_14 branch, but apparently there are still conflicts reported.
Don't hesitate to modify it yourself, I don't care about the credit.

**Comment by ChrisTruncer** [comment]
Going to close this for now since it was said this will be a little while.  If you are interested, feel free to re-submit with the module in a new pull request.

**Pull request closed without merging**
